In [1]:
import pandas as pd

In [2]:
clean_df = pd.read_csv("../data/cleaned/healthcare_cleaned.csv")

clean_df.head()

,doc_id,title,category,icd10_code,document_type,content_text,symptoms,treatments,risk_factors,prevention,...,is_contagious,target_audience,language,source_name,source_url,last_updated,word_count,reading_level_score,evidence_level,review_status
0,DOC-E6C0C42D,Conjunctivitis (Pink Eye) - Symptom Guide,Ophthalmologic,H10,Symptom Guide,Patients with Conjunctivitis (Pink Eye) common...,Redness in the white of the eye; increased tea...,Viral conjunctivitis is managed with supportiv...,Close contact with infected individuals; aller...,"Frequent handwashing, avoiding touching or rub...",...,Yes,Patient Education,en,CDC - Conjunctivitis,https://www.cdc.gov/conjunctivitis/index.html,2025-11-05,45,7.1,C,Peer-Reviewed
1,DOC-044236DE,Urinary Tract Infection - Clinical Decision Su...,Infectious,N39,Clinical Summary,Clinical decision support summary for Urinary ...,"Strong, persistent urge to urinate; burning se...","Short course of antibiotics (e.g., nitrofurant...",Female anatomy; sexual activity; certain types...,"Adequate hydration, urinating after intercours...",...,No,Clinician,en,NIDDK - Urinary Tract Infections,https://www.niddk.nih.gov/health-information/u...,2024-05-29,75,18.0,A,Peer-Reviewed
2,DOC-FDAC856F,What are the common symptoms of Major Depressi...,Mental Health,F32,FAQ,Q: What are the common symptoms of Major Depre...,Persistent sad or empty mood; loss of interest...,"Psychotherapy (cognitive behavioral therapy, i...",Family history of depression; history of traum...,"Stress management, strong social support netwo...",...,No,General Public,en,NIMH - Depression,https://www.nimh.nih.gov/health/topics/depression,2024-05-08,42,8.0,C,Peer-Reviewed
3,DOC-79AD337F,Is Essential Hypertension contagious?,Cardiovascular,I10,FAQ,Q: Is Essential Hypertension contagious? A: Ba...,Often asymptomatic; occasional headaches; shor...,"Lifestyle changes (DASH diet, sodium reduction...",High sodium intake; obesity; sedentary lifesty...,"Reducing dietary sodium, maintaining healthy w...",...,No,Patient Education,en,American Heart Association - High Blood Pressure,https://www.heart.org/en/health-topics/high-bl...,2027-03-09,22,8.9,C,Peer-Reviewed
4,DOC-90A8B2C8,What is Psoriasis?,Dermatologic,L40,FAQ,Q: What is Psoriasis? A: Psoriasis is a chroni...,"Red patches of skin covered with thick, silver...","Topical treatments (corticosteroids, vitamin D...",Family history of psoriasis; smoking; obesity;...,No definitive prevention exists; managing trig...,...,No,General Public,en,CDC - Psoriasis,https://www.cdc.gov/psoriasis/index.html,2025-07-15,34,9.8,B,Peer-Reviewed

In [3]:
text_columns = [
    "title",
    "content_text",
    "symptoms",
    "treatments",
    "risk_factors",
    "prevention"
]

In [4]:
clean_df[text_columns].head(2)

,title,content_text,symptoms,treatments,risk_factors,prevention
0,Conjunctivitis (Pink Eye) - Symptom Guide,Patients with Conjunctivitis (Pink Eye) common...,Redness in the white of the eye; increased tea...,Viral conjunctivitis is managed with supportiv...,Close contact with infected individuals; aller...,"Frequent handwashing, avoiding touching or rub..."
1,Urinary Tract Infection - Clinical Decision Su...,Clinical decision support summary for Urinary ...,"Strong, persistent urge to urinate; burning se...","Short course of antibiotics (e.g., nitrofurant...",Female anatomy; sexual activity; certain types...,"Adequate hydration, urinating after intercours..."

In [5]:
def create_text(row):
    return f"""
Title: {row['title']}

Content:
{row['content_text']}

Symptoms:
{row['symptoms']}

Treatments:
{row['treatments']}

Risk Factors:
{row['risk_factors']}

Prevention:
{row['prevention']}
""".strip()

In [6]:
clean_df["text"] = clean_df.apply(create_text, axis=1)

In [7]:
print(clean_df["text"].iloc[0])

Title: Conjunctivitis (Pink Eye) - Symptom Guide

Content:
Patients with Conjunctivitis (Pink Eye) commonly present with the following symptoms: Redness in the white of the eye; increased tear production; itchy or burning eyes; discharge (watery, mucous, or pus-like); blurred vision; crusting of eyelids. Symptom severity and combination vary by individual and disease stage.

Symptoms:
Redness in the white of the eye; increased tear production; itchy or burning eyes; discharge (watery, mucous, or pus-like); blurred vision; crusting of eyelids

Treatments:
Viral conjunctivitis is managed with supportive care (cool compresses, artificial tears). Bacterial conjunctivitis may require antibiotic eye drops. Allergic conjunctivitis is treated with antihistamine eye drops.

Risk Factors:
Close contact with infected individuals; allergies; contact lens use; exposure to irritants; recent upper respiratory infection

Prevention:
Frequent handwashing, avoiding touching or rubbing the eyes, not sharing personal items such as towels, and proper contact lens hygiene.

In [5]:
from sentence_transformers import SentenceTransformer

c:\Users\DELL\OneDrive\Desktop\health care chatbot\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [6]:
model = SentenceTransformer("all-MiniLM-L6-v2")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
c:\Users\DELL\OneDrive\Desktop\health care chatbot\.venv\Lib\site-packages\huggingface_hub\file_download.py:142: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\DELL\.cache\huggingface\hub\models--sentence-transformers--all-MiniLM-L6-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 1352.53it/s]

In [11]:
import pandas as pd

In [15]:
def create_text(row):
    return f"""
Title: {row['title']}

Content:
{row['content_text']}

Symptoms:
{row['symptoms']}

Treatments:
{row['treatments']}

Risk Factors:
{row['risk_factors']}

Prevention:
{row['prevention']}
""".strip()

In [16]:
clean_df["text"] = clean_df.apply(create_text, axis=1)

In [17]:
print(clean_df["text"].iloc[0])

Title: Conjunctivitis (Pink Eye) - Symptom Guide

Content:
Patients with Conjunctivitis (Pink Eye) commonly present with the following symptoms: Redness in the white of the eye; increased tear production; itchy or burning eyes; discharge (watery, mucous, or pus-like); blurred vision; crusting of eyelids. Symptom severity and combination vary by individual and disease stage.

Symptoms:
Redness in the white of the eye; increased tear production; itchy or burning eyes; discharge (watery, mucous, or pus-like); blurred vision; crusting of eyelids

Treatments:
Viral conjunctivitis is managed with supportive care (cool compresses, artificial tears). Bacterial conjunctivitis may require antibiotic eye drops. Allergic conjunctivitis is treated with antihistamine eye drops.

Risk Factors:
Close contact with infected individuals; allergies; contact lens use; exposure to irritants; recent upper respiratory infection

Prevention:
Frequent handwashing, avoiding touching or rubbing the eyes, not sharing personal items such as towels, and proper contact lens hygiene.

In [18]:
embedding = model.encode(clean_df["text"].iloc[0])

In [13]:
clean_df = pd.read_csv("../data/cleaned/healthcare_cleaned.csv")

In [19]:
embedding.shape

(384,)

In [20]:
embeddings = model.encode(
    clean_df["text"].tolist(),
    show_progress_bar=True
)

Batches: 100%|██████████| 13/13 [00:26<00:00,  2.07s/it]

In [21]:
embeddings.shape

(409, 384)

In [22]:
import faiss

In [23]:
import numpy as np

In [24]:
embeddings = np.asarray(embeddings).astype("float32")

In [25]:
faiss.normalize_L2(embeddings)

In [26]:
index = faiss.IndexFlatIP(384)

In [27]:
index.add(embeddings)

In [28]:
index.ntotal

409

In [29]:
query = "What are the symptoms of pink eye?"

In [30]:
query_embedding = model.encode([query])

In [31]:
query_embedding = np.asarray(query_embedding).astype("float32")

In [32]:
faiss.normalize_L2(query_embedding)

In [33]:
scores, indices = index.search(query_embedding, 3)

In [34]:
indices

array([[126,   0,  49]])

In [35]:
scores

array([[0.68337464, 0.63645387, 0.61113954]], dtype=float32)

In [36]:
for idx, score in zip(indices[0], scores[0]):
    print("Score:", score)
    print("Title:", clean_df.iloc[idx]["title"])
    print("-" * 80)

Score: 0.68337464
Title: What are the common symptoms of Conjunctivitis (Pink Eye)?
--------------------------------------------------------------------------------
Score: 0.63645387
Title: Conjunctivitis (Pink Eye) - Symptom Guide
--------------------------------------------------------------------------------
Score: 0.61113954
Title: Conjunctivitis (Pink Eye) - Overview
--------------------------------------------------------------------------------

In [37]:
import os
import faiss

os.makedirs("../backend/vector_store", exist_ok=True)

faiss.write_index(
    index,
    "../backend/vector_store/healthcare.index"
)

print("FAISS index saved successfully!")

FAISS index saved successfully!

In [38]:
import pickle

with open("../backend/vector_store/documents.pkl", "wb") as f:
    pickle.dump(clean_df.to_dict("records"), f)

print("Documents saved successfully!")

Documents saved successfully!

In [39]:
import faiss
import pickle

# Load FAISS index
loaded_index = faiss.read_index(
    "../backend/vector_store/healthcare.index"
)

# Load documents
with open("../backend/vector_store/documents.pkl", "rb") as f:
    loaded_documents = pickle.load(f)

print("Index loaded:", loaded_index.ntotal)
print("Documents loaded:", len(loaded_documents))

Index loaded: 409
Documents loaded: 409